# This is a basic workflow to help you get started with Actions

name: Clean old releases

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "clean"
  clean:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clean old releases
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: opaqueTree/td_release
          keep_latest: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
